const STORAGE_KEY='paychase.invoices.v1';
let invoices=loadInvoices();let activeInvoiceId=null;let activeTone='friendly';
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
function loadInvoices(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||[]}catch{return[]}}
function saveInvoices(){localStorage.setItem(STORAGE_KEY,JSON.stringify(invoices))}
function money(v){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(Number(v)||0)}
function localDate(value){if(!value)return null;const [y,m,d]=value.split('-').map(Number);return new Date(y,m-1,d)}
function daysLate(invoice){if(invoice.status==='paid')return 0;const due=localDate(invoice.dueDate);const today=new Date();today.setHours(0,0,0,0);return Math.max(0,Math.floor((today-due)/86400000))}
function invoiceStatus(i){if(i.status==='paid')return'paid';return daysLate(i)>0?'overdue':'open'}
function escapeHTML(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function render(){const open=invoices.filter(i=>i.status!=='paid');const overdue=open.filter(i=>daysLate(i)>0);const paid=invoices.filter(i=>i.status==='paid');$('#outstandingTotal').textContent=money(open.reduce((s,i)=>s+Number(i.amount),0));$('#overdueTotal').textContent=money(overdue.reduce((s,i)=>s+Number(i.amount),0));$('#recoveredTotal').textContent=money(paid.reduce((s,i)=>s+Number(i.amount),0));$('#focusCount').textContent=`${overdue.length} ${overdue.length===1?'invoice':'invoices'}`;$('#focusMeta').textContent=overdue.length?`${money(overdue.reduce((s,i)=>s+Number(i.amount),0))} currently overdue.`:'Nothing needs attention yet.';renderList()}
function renderList(){const q=$('#searchInput').value.trim().toLowerCase();const filter=$('#statusFilter').value;let list=invoices.filter(i=>{const st=invoiceStatus(i);return(!q||i.client.toLowerCase().includes(q)||i.invoiceNumber.toLowerCase().includes(q))&&(filter==='all'||st===filter)});list.sort((a,b)=>a.status==='paid'-b.status==='paid'||localDate(a.dueDate)-localDate(b.dueDate));const root=$('#invoiceList');if(!list.length){root.innerHTML=`<div class="empty"><strong>${invoices.length?'No matching invoices':'No invoices yet'}</strong>${invoices.length?'Try changing your search or filter.':'Add your first invoice to start tracking follow-ups.'}</div>`;return}root.innerHTML=list.map(i=>{const st=invoiceStatus(i),late=daysLate(i);return `<article class="invoice-row"><div><div class="invoice-client">${escapeHTML(i.client)}</div><div class="invoice-sub">${escapeHTML(i.invoiceNumber)}${i.email?` · ${escapeHTML(i.email)}`:''}</div></div><div><div class="amount">${money(i.amount)}</div><div class="invoice-sub">Due ${localDate(i.dueDate).toLocaleDateString()}</div></div><div><span class="status ${st}">${st}</span><div class="invoice-sub">${st==='overdue'?`${late} day${late===1?'':'s'} late`:st==='paid'?'Payment recorded':'Not due yet'}</div></div><div class="row-actions">${st!=='paid'?`<button class="mini-btn" data-action="remind" data-id="${i.id}">Reminder</button><button class="mini-btn" data-action="paid" data-id="${i.id}">Mark paid</button>`:''}<button class="mini-btn" data-action="delete" data-id="${i.id}">Delete</button></div></article>`}).join('')}
function openModal(id){$(id).classList.remove('hidden')};function closeModal(id){$(id).classList.add('hidden')}
function reminderFor(i,tone){const late=daysLate(i);const due=localDate(i.dueDate).toLocaleDateString();const hello=`Hi ${i.client},`;const details=`invoice ${i.invoiceNumber} for ${money(i.amount)}, due ${due}`;if(tone==='firm')return `${hello}\n\nI’m following up regarding ${details}. ${late?`It is now ${late} day${late===1?'':'s'} overdue. `:''}Please arrange payment as soon as possible or let me know today if there is an issue preventing payment.\n\nThank you.`;if(tone==='standard')return `${hello}\n\nI’m following up on ${details}. ${late?'The invoice is currently overdue. ':''}Could you please confirm when payment is expected?\n\nThank you.`;return `${hello}\n\nJust a quick reminder about ${details}. ${late?'It looks like the due date has passed. ':''}When you have a moment, could you let me know the payment status?\n\nThanks so much!`}
function refreshReminder(){const i=invoices.find(x=>x.id===activeInvoiceId);if(i)$('#reminderText').value=reminderFor(i,activeTone)}
$('#openInvoiceModal').addEventListener('click',()=>openModal('#invoiceModal'));$('#closeInvoiceModal').addEventListener('click',()=>closeModal('#invoiceModal'));$('#cancelInvoice').addEventListener('click',()=>closeModal('#invoiceModal'));$('#closeReminderModal').addEventListener('click',()=>closeModal('#reminderModal'));$('#closeReminder').addEventListener('click',()=>closeModal('#reminderModal'));
$('#invoiceForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);invoices.push({id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),client:f.get('client').trim(),invoiceNumber:f.get('invoiceNumber').trim(),amount:Number(f.get('amount')),dueDate:f.get('dueDate'),email:f.get('email').trim(),status:'open',createdAt:new Date().toISOString()});saveInvoices();e.currentTarget.reset();closeModal('#invoiceModal');render();toast('Invoice saved')});
$('#invoiceList').addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const i=invoices.find(x=>x.id===b.dataset.id);if(!i)return;if(b.dataset.action==='paid'){i.status='paid';i.paidAt=new Date().toISOString();saveInvoices();render();toast('Invoice marked paid')}if(b.dataset.action==='delete'){if(confirm(`Delete ${i.invoiceNumber}?`)){invoices=invoices.filter(x=>x.id!==i.id);saveInvoices();render()}}if(b.dataset.action==='remind'){activeInvoiceId=i.id;activeTone=daysLate(i)>=14?'firm':daysLate(i)>=7?'standard':'friendly';$$('.tone-btn').forEach(x=>x.classList.toggle('active',x.dataset.tone===activeTone));refreshReminder();openModal('#reminderModal')}});
$$('.tone-btn').forEach(b=>b.addEventListener('click',()=>{activeTone=b.dataset.tone;$$('.tone-btn').forEach(x=>x.classList.toggle('active',x===b));refreshReminder()}));
$('#copyReminder').addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('#reminderText').value);toast('Reminder copied')}catch{$('#reminderText').select();document.execCommand('copy');toast('Reminder copied')}});$('#searchInput').addEventListener('input',renderList);$('#statusFilter').addEventListener('change',renderList);
function toast(msg){const el=document.createElement('div');el.className='toast';el.textContent=msg;document.body.appendChild(el);setTimeout(()=>el.remove(),1800)}
render();
